argo-cd:
  dex:
    # -- Enable dex
    enabled: false
  fullnameOverride: argocd
  apiVersionOverrides:
    ingress: networking.k8s.io/v1
  global:
    domain: ""
  configs:
    cm:
      accounts.jenkins: apiKey
      accounts.nlee: login
      accounts.rudgh21: login, apiKey
      admin.enabled: "false"
      url: http://rudgh21.com
    rbac:
      policy.csv: |
            p, role:readonly, logs, get, */*, allow
            p, role:admin, *, *, */*, allow
            p, role:admin, logs, get, */*, allow
            g, jenkins, role:admin
            g, nlee, role:admin
            g, rudgh21, role:admin
      policy.default: role:readonly
      scopes: "[email,groups]"
    params:
      server.insecure: true
    secret:
      createSecret: true
      extra:
        {
          # TODO
          # argo 1회 생성후, 서버에서 Token 발행 필요
          accounts.jenkins.tokens: '[{"id":"0688fc45-de10-4d78-8558-8e75cf67edea","iat":1714622812000}]',
          accounts.nlee.password: "$2a$10$rRyBsGSHK6.uc8fntPwVIuLVHgsAhAX7TcdrqW/RADU0uh7CaChLa",
          accounts.rudgh21.password: "$2a$10$rRyBsGSHK6.uc8fntPwVIuLVHgsAhAX7TcdrqW/RADU0uh7CaChLa"
        }
      argocdServerAdminPassword: "$2a$10$rRyBsGSHK6.uc8fntPwVIuLVHgsAhAX7TcdrqW/RADU0uh7CaChLa"
      argocdServerAdminPasswordMtime: "'$(date +%FT%T%Z)'"
    repositories:
      {
          url: https://github.com/rodgh21/AzureTest_JAVA.git,
          url: https://github.com/rodgh21/argo-deploy.git
      }
      



  repoServer:
    resources:
      requests:
        cpu: 0.5
        memory: 450Mi
    autoscaling:
      # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
      enabled: true
      # -- Minimum number of replicas for the repo server [HPA]
      minReplicas: 1
      # -- Maximum number of replicas for the repo server [HPA]
      maxReplicas: 5
      # -- Average CPU utilization percentage for the repo server [HPA]
      targetCPUUtilizationPercentage: 50
      # -- Average memory utilization percentage for the repo server [HPA]
      targetMemoryUtilizationPercentage: 50
      # -- Configures the scaling behavior of the target in both Up and Down directions.
      # This is only available on HPA apiVersion `autoscaling/v2beta2` and newer
      behavior:
        {}
        # scaleDown:
        #  stabilizationWindowSeconds: 300
        #  policies:
        #   - type: Pods
        #     value: 1
        #     periodSeconds: 180
        # scaleUp:
        #   stabilizationWindowSeconds: 300
        #   policies:
        #   - type: Pods
        #     value: 2
        #     periodSeconds: 60

  controller:
    resources:
      requests:
        cpu: 0.5
        memory: 450Mi
    serviceAccount:
      # -- Create a service account for the application controller
      create: true
      # -- Service account name
      name: argocd-application-controller
      # -- Annotations applied to created service account
      # annotations:
      #   {
      #     # TODO
      #     # AICC Role 확인 필요
      #     eks.amazonaws.com/role-arn: arn:aws:iam::992382711213:role/eks-aicc-argo,
      #   }
      # # -- Automount API credentials for the Service Account
      # automountServiceAccountToken: false

  server:
    extraArgs:
      - "--insecure"
      - "--port"
      - "7080"
    resources:
      requests:
        cpu: 0.5
        memory: 450Mi
    serviceAccount:
      # -- Create server service account
      create: true
      # -- Server service account name
      name: argocd-server
      # -- Annotations applied to created service account
      # annotations:
      #   {
      #     # TODO
      #     # AICC Role 확인 필요
      #     eks.amazonaws.com/role-arn: arn:aws:iam::992382711213:role/eks-aicc-argo,
      #   }
      # # -- Automount API credentials for the Service Account
      automountServiceAccountToken: true
    autoscaling:
      enabled: true
      # -- Minimum number of replicas for the Argo CD server [HPA]
      minReplicas: 1
      # -- Maximum number of replicas for the Argo CD server [HPA]
      maxReplicas: 5
      # -- Average CPU utilization percentage for the Argo CD server [HPA]
      targetCPUUtilizationPercentage: 50
      # -- Average memory utilization percentage for the Argo CD server [HPA]
      targetMemoryUtilizationPercentage: 50
    containerPorts: 
      server: 7080
      metrics: 7083
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: rudgh21.com
      extraPaths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 80